# Берем легкую версию Python
FROM python:3.12-slim

# Устанавливаем рабочую папку внутри контейнера
WORKDIR /app

# Устанавливаем системные зависимости для научных библиотек
RUN apt-get update && apt-get install -y \
    build-essential \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

# Копируем список зависимостей и ставим их
COPY dashboard/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем наши файлы в контейнер
COPY dashboard dashboard/
COPY main.py .
COPY .streamlit .streamlit

# Создаем secrets.toml для Docker с правильным URL API
RUN echo 'api_url = "http://time_series_api:8000/api/"' > .streamlit/secrets.toml

EXPOSE $PORT

CMD sh -c "streamlit run main.py --server.port $PORT --server.address 0.0.0.0 --logger.level=warning"
