# Берем легкую версию Python
FROM python:3.12-slim

# Устанавливаем рабочую папку внутри контейнера
WORKDIR /app

# Устанавливаем системные зависимости для научных библиотек
RUN apt-get update && apt-get install -y \
    build-essential \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

# Копируем список зависимостей и ставим их
COPY dashboard/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем наши файлы в контейнер
COPY dashboard dashboard/
COPY main.py .
COPY .streamlit .streamlit

#RUN mkdir -p .streamlit

EXPOSE $PORT

# Создаем config.toml
#RUN echo "[server]\n\
#port = ${PORT:-8501}\n\
#fileWatcherType = \"poll\"" > .streamlit/config.toml
#
#RUN echo "api_url = \"http://time_series_api:8000/api/\"" > .streamlit/secrets.toml

CMD sh -c "streamlit run main.py --server.port $PORT --server.address 0.0.0.0"
