FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./API/app/

EXPOSE $PORT

CMD sh -c "uvicorn API.app.main:app --host 0.0.0.0 --port $PORT"