FROM python:3.12-slim

WORKDIR /code/API

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app/

EXPOSE $PORT

CMD sh -c "cd /code && uvicorn API.app.main:app --host 0.0.0.0 --port $PORT"